### ISSUE TITLE
TypeError: player1.play is not a function

### ISSUE THREAD

**Issue by renep16** [mingxinstar/react-hls#10]
Hi, is this able to start play from javascript and not from user click? I want to fire play when someone click on a external button

**Comment by devcshort** [comment]
It seems like this project is no longer maintained. If you'd like I've forked this project and fixed some issues. It's available on npm as react-hls-player, and can also be found on my git profile.

I recently added in the ability to pass in your own React Ref which will allow you to control the video player directly using javascript.
