### ISSUE TITLE
looping not supported in attributes.

### ISSUE THREAD

**Issue by ghost** [mingxinstar/react-hls#3]
Hi, I could not set loop="true" to make the video loop through. How should I achieve this? Thanks.

**Comment by mingxinstar** [comment]
@poovizhichandramohan I have added a property `videoProps` to support your feature. Now you can simply add a property like this:
```javascript
import ReactHLS from 'react-hls';

<ReactHLS url='http://test.m3u8' videoProps={{ loop : true }} />
```
